### PR TITLE
Using npm_config_* environment variables instead of sourcing npmrc

### PR DESCRIPTION
**Pull request by alash3**
Hi,

I noticed you are using only the .npmrc file, but not the values that can be passed to npm via cli arguments. This PR switches that. Let me know your thoughts.

Thanks,
Albert

### CODE REVIEW

**Comment by kevva** [comment]
Why would you remove the ones from `.npmrc`? We can have both.

**Comment by alash3** [comment]
The npm_config_\* environment variables take the .npmrc into consideration, so they aren't removed, they are replaced.

**Comment by sindresorhus** [comment]
`npm_config` env vars are only available when the code is run as in a npm run script. It should have both.

**Comment by alash3** [comment]
I disagree; npm-specific configurations need to stay npm specific. The proxy settings used when not running as an npm script should respect environment variables.

The current design of get-proxy does not support the no_proxy environment variable. Are you planning on supporting that?

**Comment by kevva** [comment]
#6 will take read CLI arguments (when ran as a npm script). Going to close this in favor of that. Feel free to open new issues if you want more variables or taking CLI arguments outside of npm scripts into account.

**Pull request closed without merging**
